### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/tmp/tmpkDgYpg.HelT'

### ISSUE THREAD

**Issue by VoDanh134** [amathelier/DNAshapedTFBS#3]
No such file or directory
 to read0.HelT.wig.bwnh/NCKH/DNAshapedTFBS/test/DNAShape
Traceback (most recent call last):
  File "../DNAshapedTFBS.py", line 225, in <module>
    arguments.func(arguments)
  File "/home/vodanh/NCKH/DNAshapedTFBS/DNAshapedTFBS.py", line 156, in pssm_apply_classifier
    apply_classifier(hits, argu)
  File "/home/vodanh/NCKH/DNAshapedTFBS/DNAshapedTFBS.py", line 125, in apply_classifier
    argu.second_shape, argu.extension, argu.scaled)
  File "/home/vodanh/NCKH/DNAshapedTFBS/shapes.py", line 73, in get_shapes
    hits_shapes.append(get_scores(out_file, shapes[indx], scaled))
  File "/home/vodanh/NCKH/DNAshapedTFBS/shapes.py", line 7, in get_scores
    with open(in_file) as stream:
IOError: [Errno 2] No such file or directory: '/tmp/tmpkDgYpg.HelT'

Can u help me?

**Comment by amathelier** [comment]
Looks like the computation of the HelT feature values went wrong. Hard to know what is going on without the input file and the exact command used. Are you able to run the provided test run?

**Comment by VoDanh134** [comment]
@amathelier Hi. Sorry to reply late. I've got that error when I tried to run file test.sh. It seems that it couldn't create file .HelT. I changed outfile in function get_shapes in shapes.py to "1.txt" to check the bwtool command if it worked. It worked but I've got another error.

`Traceback (most recent call last):
  File "../DNAshapedTFBS.py", line 228, in <module>
    arguments.func(arguments)
  File "/home/vodanh/NCKH/DNAshapedTFBS/DNAshapedTFBS.py", line 198, in tffm_train_classifier
    train_classifier(fg_hits, bg_hits, argu)
  File "/home/vodanh/NCKH/DNAshapedTFBS/DNAshapedTFBS.py", line 190, in train_classifier
    argu.extension, bool4bits)
  File "/home/vodanh/NCKH/DNAshapedTFBS/DNAshapedTFBS.py", line 75, in fit_classifier
    bool4bits)
  File "/home/vodanh/NCKH/DNAshapedTFBS/shapes.py", line 37, in combine_hits_shapes
    hit_shapes += shapes[indx][index]
IndexError: list index out of range
`

And it showed 
No such file or directory
 to read0.HelT.wig.bwnh/NCKH/DNAshapedTFBS/test/DNAShape
No such file or directory
 to read0.ProT.wig.bwnh/NCKH/DNAshapedTFBS/test/DNAShape
No such file or directory
 to read0.MGW.wig.bwanh/NCKH/DNAshapedTFBS/test/DNAShape
No such file or directory
 to read0.Roll.wig.bwnh/NCKH/DNAshapedTFBS/test/DNAShape
No such file or directory

I wonder if I should install something to be able to create file .HelT or should change path somewhere?
Thank you

**Comment by amathelier** [comment]
Hi. It looks like there is a problem creating the temporary files. Are you sure you have write permission in the directories?
